### ISSUE TITLE
Support for style copy

### ISSUE THREAD

**Issue by bmaltais** [DmitryUlyanov/fast-neural-doodle#1]
Hello Dmitry, this is very nice. I appreciate the speed your implementation provide.

I have a question, do you intend to add support for simple style copy instead of doodle based on mask file? This is a simpler alternative that I found to provide better results at times.

Regards

**Comment by DmitryUlyanov** [comment]
Hey, I'm sorry, I do not understand what "simple style copy" is.. Isn't it the style copy which is done by artistic style algorithm? Please detail. 

Dmitry

**Comment by bmaltais** [comment]
Hi, perhaps style transfer is a better term. The command from neural-doodle when doing style-transfer vs Image Analogy is:

python3 doodle.py --style samples/Gogh.jpg --content samples/Seth.png \
                  --output SethAsGogh.png --device=cpu --iterations=40

In that case there is no need to provide a mask. Just a simple style and content image.

**Comment by DmitryUlyanov** [comment]
Well, if my method is extended to style transfer it naturally becomes artistic style :) So there's nothing new I can do, I suppose.
